name: panda_helper
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.12
    - beautifulsoup4=4.12.3
    - black=24.4.2
    - build=0.7.0
    - codespell
    - coverage=7.2.2
    - jupyter=1.0.0
    - lxml=5.2.1
    - mkdocs=1.6.0
    - notebook=7.0.8
    - numpy=1.26.4
    - pandas=2.2.2
    - pip=24.0
    - pre-commit=3.4.0
    - pylint=3.2.2
    - pytest=7.4.4
    - ruff=0.3.5
    - scipy=1.13.1
    - twine=4.0.2
    - pip:
        - mkdocs-material==9.5.28
        - mkdocstrings==0.25.1
        - mkdocstrings-python==1.10.5
        - tabulate==0.9.0
