site_name: Panda-Helper
site_url: https://ray310.github.io/Panda-Helper/
repo_url: https://github.com/ray310/Panda-Helper
site_author: ray310
site_description: Panda-Helper documentation
copyright: >
  Copyright &copy 2022-2024 Ray310 -
  <a href="#__consent">Change cookie settings</a>
nav:
  - Home: index.md
  - Installation: install.md
  - User Guide: user_guide.md
  - API Reference: api.md
  - Issue Tracker: https://github.com/ray310/Panda-Helper/issues
extra_css:
  - stylesheets/extra.css
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

theme:
  name: material
  custom_dir: docs/overrides
  favicon: assets/images/panda.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - toc.integrate
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
    logo: material/panda

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
          - accept
          - reject
          - manage
  analytics:
    provider: google
    property: G-YD5R7VPW02
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            We are glad the page was helpful. Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/ray310/Panda-Helper/issues/new/?title=[Feedback]+{title}" target="_blank" rel="noopener">feedback form</a>.
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ray310/Panda-Helper
      name: Ray310 on GitHub
markdown_extensions:
  - attr_list
  - md_in_html
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          docstring_style: google
          docstring_section_style: list
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          annotations_path: full
          separate_signature: true
          line_length: 80
          show_category_heading: false
          show_root_heading: true
          show_source: false
          filters:
            - "!^_"
            - "!dist_stats_dict"
